{% set name = "DateTimeRange" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 3bd37ed3f18ff279ffa520ee58c5a3362236c5b4bb052f781a7e2260e1a24764

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - typepy >=1.0.0,<2
    - python-dateutil >=2.4.2,<3

test:
  imports:
    - datetimerange
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/thombashi/DateTimeRange
  summary: DateTimeRange is a Python library to handle a time range.
  description: |
    Check whether a time is within the time range, get the intersection of time ranges, 
    truncating a time range, iterate through a time range, and so forth.
  dev_url: https://github.com/thombashi/DateTimeRange
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kthyng
