{% set name = "DateTimeRange" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 55a999d205d6aae73d526b6c38325c25b67a918285354770c5d494f595e9f1e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - typepy >=1.0.0,<2
    - python-dateutil >=2.4.2,<3

test:
  imports:
    - datetimerange
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/thombashi/DateTimeRange
  summary: DateTimeRange is a Python library to handle a time range.
  description: |
    Check whether a time is within the time range, get the intersection of time ranges, 
    truncating a time range, iterate through a time range, and so forth.
  dev_url: https://github.com/thombashi/DateTimeRange
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kthyng
